on: push
name: Main Workflow
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: achilleslinux/sonarqube-action@master
      with:
        host: ${{ http://localhost:9000 }}
        login: ${{ bc7326fba0c99227cd7df150277db652200ad8d4 }}
